version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devbridge-postgres
    environment:
      POSTGRES_DB: devbridge
      POSTGRES_USER: devbridge
      POSTGRES_PASSWORD: devbridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devbridge"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9-alpine
    command: migrate
    volumes:
      - ./backend/schemas/sql/migrations:/flyway/sql
    container_name: devbridge-flyway
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/devbridge
      - FLYWAY_USER=devbridge
      - FLYWAY_PASSWORD=devbridge
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql

volumes:
  postgres_data:
