version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: devbridge
      POSTGRES_USER: devbridge
      POSTGRES_PASSWORD: devbridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9-alpine
    command: -configFiles=/flyway/conf/flyway.conf migrate
    volumes:
      - ./backend/schemas/sql/migrations:/flyway/sql
      - ./backend/schemas/sql/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - postgres
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/devbridge
      - FLYWAY_USER=devbridge
      - FLYWAY_PASSWORD=devbridge

volumes:
  postgres_data:
