name: .NET Backend CI/CD

on:
  push:
    branches:
      - master
      - 'NBLMNT-*'
    paths:
      - 'backend/dotnet/**'
      - '.github/workflows/backend-dotnet.yml'
  pull_request:
    paths:
      - 'backend/dotnet/**'
      - '.github/workflows/backend-dotnet.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: backend/dotnet/**/*.csproj

      - name: Configure NuGet Sources
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/Maersk-Global/index.json" \
            --name github \
            --username alan-kelly-maersk \
            --password ${GITHUB_PAT} \
            --store-password-in-clear-text

      - name: Restore dependencies
        working-directory: backend/dotnet
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore --verbosity detailed

      - name: Build
        working-directory: backend/dotnet
        run: dotnet build --no-restore

      - name: Test
        working-directory: backend/dotnet
        run: dotnet test --no-build --verbosity normal

      - name: Import Secrets
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/vault-action@v2
        with:
          url: "https://mss.maersk.io/"
          method: jwt
          path: github-jwt
          role: "devbridge--maersk_global--devbridge"
          secrets: |
            devbridge-nonprod-kv/data/platform--harbor/devbridge server | CONTAINER_REGISTRY_SERVER;
            devbridge-nonprod-kv/data/platform--harbor/devbridge username | CONTAINER_REGISTRY_USERNAME;
            devbridge-nonprod-kv/data/platform--harbor/devbridge password | CONTAINER_REGISTRY_PASSWORD;

      - name: Login to Harbor
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY_SERVER }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/master'
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: ./backend/dotnet
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.CONTAINER_REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
