name: .NET Backend CI/CD

on:
  push:
    branches:
      - master
      - 'NBLMNT-*'
    paths:
      - 'backend/dotnet/**'
      - '.github/workflows/backend-dotnet.yml'
  pull_request:
    paths:
      - 'backend/dotnet/**'
      - '.github/workflows/backend-dotnet.yml'

env:
  REGISTRY: harbor.maersk.com
  IMAGE_NAME: devbridge/backend-dotnet

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: backend/dotnet/**/*.csproj

      - name: Configure NuGet Sources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/Maersk-Global/index.json" \
            --name github \
            --username alan-kelly-maersk \
            --password ${GITHUB_TOKEN} \
            --store-password-in-clear-text

      - name: Restore dependencies
        working-directory: backend/dotnet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore --verbosity detailed

      - name: Build
        working-directory: backend/dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: backend/dotnet
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Login to Harbor
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/master'
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: ./backend/dotnet
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
